version: "3.9"

services:
  gitea:
    image: gitea/gitea:1.22.3
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
      - GITEA__server__DOMAIN=gitea.vivindeena.xyz
      - GITEA__server__ROOT_URL=https://gitea.vivindeena.xyz/
      - GITEA__server__SSH_DOMAIN=gitea.vivindeena.xyz
      - GITEA__server__SSH_PORT=2222
      - GITEA__server__START_SSH_SERVER=true
      - GITEA__server__BUILTIN_SSH_SERVER_USER=git
    volumes:
      - /gitea-data:/data
    networks:
      - traefik-proxy
      - gitea_net
    depends_on:
      - postgres
    labels:
      # HTTP (Web UI)
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.vivindeena.xyz`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

      # TCP Router for SSH
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc"
      - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22"

  postgres:
    image: postgres:16
    container_name: gitea-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /pg-data:/var/lib/postgresql/data
    networks:
      - gitea_net

networks:
  traefik-proxy:
    external: true
  gitea_net:
    driver: bridge
