entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false   # only route containers you explicitly label

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: vivin.deena@gmail.com    # <-- change this
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

