entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: vivin.deena@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: "DEBUG"

accessLog:
  filePath: "/logs/access.log"